// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import org.sio.jnetmap.domain.Building;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Building_Roo_Configurable {
    
    declare @type: Building: @Configurable;
    
}
