// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import org.sio.jnetmap.domain.Building;

privileged aspect Building_Roo_JavaBean {
    
    public String Building.getNameBuilding() {
        return this.nameBuilding;
    }
    
    public void Building.setNameBuilding(String nameBuilding) {
        this.nameBuilding = nameBuilding;
    }
    
}
