// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.Band;
import org.sio.jnetmap.domain.BandDataOnDemand;
import org.sio.jnetmap.domain.DispatcherDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BandDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BandDataOnDemand: @Component;
    
    private Random BandDataOnDemand.rnd = new SecureRandom();
    
    private List<Band> BandDataOnDemand.data;
    
    @Autowired
    private DispatcherDataOnDemand BandDataOnDemand.dispatcherDataOnDemand;
    
    public Band BandDataOnDemand.getNewTransientBand(int index) {
        Band obj = new Band();
        setNumBand(obj, index);
        return obj;
    }
    
    public void BandDataOnDemand.setNumBand(Band obj, int index) {
        String numBand = "numBand_" + index;
        if (numBand.length() > 30) {
            numBand = numBand.substring(0, 30);
        }
        obj.setNumBand(numBand);
    }
    
    public Band BandDataOnDemand.getSpecificBand(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Band obj = data.get(index);
        Long id = obj.getId();
        return Band.findBand(id);
    }
    
    public Band BandDataOnDemand.getRandomBand() {
        init();
        Band obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Band.findBand(id);
    }
    
    public boolean BandDataOnDemand.modifyBand(Band obj) {
        return false;
    }
    
    public void BandDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Band.findBandEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Band' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Band>();
        for (int i = 0; i < 10; i++) {
            Band obj = getNewTransientBand(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
