// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.Building;
import org.sio.jnetmap.domain.BuildingDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect BuildingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BuildingDataOnDemand: @Component;
    
    private Random BuildingDataOnDemand.rnd = new SecureRandom();
    
    private List<Building> BuildingDataOnDemand.data;
    
    public Building BuildingDataOnDemand.getNewTransientBuilding(int index) {
        Building obj = new Building();
        setNameBuilding(obj, index);
        return obj;
    }
    
    public void BuildingDataOnDemand.setNameBuilding(Building obj, int index) {
        String nameBuilding = "nameBuilding_" + index;
        if (nameBuilding.length() > 30) {
            nameBuilding = nameBuilding.substring(0, 30);
        }
        obj.setNameBuilding(nameBuilding);
    }
    
    public Building BuildingDataOnDemand.getSpecificBuilding(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Building obj = data.get(index);
        Long id = obj.getId();
        return Building.findBuilding(id);
    }
    
    public Building BuildingDataOnDemand.getRandomBuilding() {
        init();
        Building obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Building.findBuilding(id);
    }
    
    public boolean BuildingDataOnDemand.modifyBuilding(Building obj) {
        return false;
    }
    
    public void BuildingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Building.findBuildingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Building' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Building>();
        for (int i = 0; i < 10; i++) {
            Building obj = getNewTransientBuilding(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
