// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sio.jnetmap.domain.Building;
import org.sio.jnetmap.domain.BuildingDataOnDemand;
import org.sio.jnetmap.domain.BuildingIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BuildingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BuildingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BuildingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BuildingIntegrationTest: @Transactional;
    
    @Autowired
    private BuildingDataOnDemand BuildingIntegrationTest.dod;
    
    @Test
    public void BuildingIntegrationTest.testCountBuildings() {
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", dod.getRandomBuilding());
        long count = Building.countBuildings();
        Assert.assertTrue("Counter for 'Building' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BuildingIntegrationTest.testFindBuilding() {
        Building obj = dod.getRandomBuilding();
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Building' failed to provide an identifier", id);
        obj = Building.findBuilding(id);
        Assert.assertNotNull("Find method for 'Building' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Building' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BuildingIntegrationTest.testFindAllBuildings() {
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", dod.getRandomBuilding());
        long count = Building.countBuildings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Building', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Building> result = Building.findAllBuildings();
        Assert.assertNotNull("Find all method for 'Building' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Building' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BuildingIntegrationTest.testFindBuildingEntries() {
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", dod.getRandomBuilding());
        long count = Building.countBuildings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Building> result = Building.findBuildingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Building' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Building' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BuildingIntegrationTest.testFlush() {
        Building obj = dod.getRandomBuilding();
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Building' failed to provide an identifier", id);
        obj = Building.findBuilding(id);
        Assert.assertNotNull("Find method for 'Building' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBuilding(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Building' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BuildingIntegrationTest.testMergeUpdate() {
        Building obj = dod.getRandomBuilding();
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Building' failed to provide an identifier", id);
        obj = Building.findBuilding(id);
        boolean modified =  dod.modifyBuilding(obj);
        Integer currentVersion = obj.getVersion();
        Building merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Building' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BuildingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", dod.getRandomBuilding());
        Building obj = dod.getNewTransientBuilding(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Building' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Building' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Building' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BuildingIntegrationTest.testRemove() {
        Building obj = dod.getRandomBuilding();
        Assert.assertNotNull("Data on demand for 'Building' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Building' failed to provide an identifier", id);
        obj = Building.findBuilding(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Building' with identifier '" + id + "'", Building.findBuilding(id));
    }
    
}
