// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.NetModule;
import org.sio.jnetmap.domain.NetModuleDataOnDemand;
import org.sio.jnetmap.domain.NetSwitchDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NetModuleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NetModuleDataOnDemand: @Component;
    
    private Random NetModuleDataOnDemand.rnd = new SecureRandom();
    
    private List<NetModule> NetModuleDataOnDemand.data;
    
    @Autowired
    private NetSwitchDataOnDemand NetModuleDataOnDemand.netSwitchDataOnDemand;
    
    public NetModule NetModuleDataOnDemand.getNewTransientNetModule(int index) {
        NetModule obj = new NetModule();
        setNumNetModule(obj, index);
        return obj;
    }
    
    public void NetModuleDataOnDemand.setNumNetModule(NetModule obj, int index) {
        int numNetModule = index;
        obj.setNumNetModule(numNetModule);
    }
    
    public NetModule NetModuleDataOnDemand.getSpecificNetModule(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NetModule obj = data.get(index);
        Long id = obj.getId();
        return NetModule.findNetModule(id);
    }
    
    public NetModule NetModuleDataOnDemand.getRandomNetModule() {
        init();
        NetModule obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NetModule.findNetModule(id);
    }
    
    public boolean NetModuleDataOnDemand.modifyNetModule(NetModule obj) {
        return false;
    }
    
    public void NetModuleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NetModule.findNetModuleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NetModule' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NetModule>();
        for (int i = 0; i < 10; i++) {
            NetModule obj = getNewTransientNetModule(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
