// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.DispatcherDataOnDemand;
import org.sio.jnetmap.domain.NetSwitch;
import org.sio.jnetmap.domain.NetSwitchDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NetSwitchDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NetSwitchDataOnDemand: @Component;
    
    private Random NetSwitchDataOnDemand.rnd = new SecureRandom();
    
    private List<NetSwitch> NetSwitchDataOnDemand.data;
    
    @Autowired
    private DispatcherDataOnDemand NetSwitchDataOnDemand.dispatcherDataOnDemand;
    
    public NetSwitch NetSwitchDataOnDemand.getNewTransientNetSwitch(int index) {
        NetSwitch obj = new NetSwitch();
        setIpNetSwitch(obj, index);
        setNameNetSwitch(obj, index);
        return obj;
    }
    
    public void NetSwitchDataOnDemand.setIpNetSwitch(NetSwitch obj, int index) {
        String ipNetSwitch = "ipNetSwitch_" + index;
        if (ipNetSwitch.length() > 30) {
            ipNetSwitch = ipNetSwitch.substring(0, 30);
        }
        obj.setIpNetSwitch(ipNetSwitch);
    }
    
    public void NetSwitchDataOnDemand.setNameNetSwitch(NetSwitch obj, int index) {
        String nameNetSwitch = "nameNetSwitch_" + index;
        if (nameNetSwitch.length() > 30) {
            nameNetSwitch = nameNetSwitch.substring(0, 30);
        }
        obj.setNameNetSwitch(nameNetSwitch);
    }
    
    public NetSwitch NetSwitchDataOnDemand.getSpecificNetSwitch(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NetSwitch obj = data.get(index);
        Long id = obj.getId();
        return NetSwitch.findNetSwitch(id);
    }
    
    public NetSwitch NetSwitchDataOnDemand.getRandomNetSwitch() {
        init();
        NetSwitch obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NetSwitch.findNetSwitch(id);
    }
    
    public boolean NetSwitchDataOnDemand.modifyNetSwitch(NetSwitch obj) {
        return false;
    }
    
    public void NetSwitchDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NetSwitch.findNetSwitchEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NetSwitch' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NetSwitch>();
        for (int i = 0; i < 10; i++) {
            NetSwitch obj = getNewTransientNetSwitch(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
