// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sio.jnetmap.domain.NetSwitch;
import org.sio.jnetmap.domain.NetSwitchDataOnDemand;
import org.sio.jnetmap.domain.NetSwitchIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NetSwitchIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NetSwitchIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NetSwitchIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NetSwitchIntegrationTest: @Transactional;
    
    @Autowired
    private NetSwitchDataOnDemand NetSwitchIntegrationTest.dod;
    
    @Test
    public void NetSwitchIntegrationTest.testCountNetSwitches() {
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", dod.getRandomNetSwitch());
        long count = NetSwitch.countNetSwitches();
        Assert.assertTrue("Counter for 'NetSwitch' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NetSwitchIntegrationTest.testFindNetSwitch() {
        NetSwitch obj = dod.getRandomNetSwitch();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to provide an identifier", id);
        obj = NetSwitch.findNetSwitch(id);
        Assert.assertNotNull("Find method for 'NetSwitch' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'NetSwitch' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NetSwitchIntegrationTest.testFindAllNetSwitches() {
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", dod.getRandomNetSwitch());
        long count = NetSwitch.countNetSwitches();
        Assert.assertTrue("Too expensive to perform a find all test for 'NetSwitch', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<NetSwitch> result = NetSwitch.findAllNetSwitches();
        Assert.assertNotNull("Find all method for 'NetSwitch' illegally returned null", result);
        Assert.assertTrue("Find all method for 'NetSwitch' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NetSwitchIntegrationTest.testFindNetSwitchEntries() {
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", dod.getRandomNetSwitch());
        long count = NetSwitch.countNetSwitches();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<NetSwitch> result = NetSwitch.findNetSwitchEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'NetSwitch' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'NetSwitch' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NetSwitchIntegrationTest.testFlush() {
        NetSwitch obj = dod.getRandomNetSwitch();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to provide an identifier", id);
        obj = NetSwitch.findNetSwitch(id);
        Assert.assertNotNull("Find method for 'NetSwitch' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNetSwitch(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'NetSwitch' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NetSwitchIntegrationTest.testMergeUpdate() {
        NetSwitch obj = dod.getRandomNetSwitch();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to provide an identifier", id);
        obj = NetSwitch.findNetSwitch(id);
        boolean modified =  dod.modifyNetSwitch(obj);
        Integer currentVersion = obj.getVersion();
        NetSwitch merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'NetSwitch' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NetSwitchIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", dod.getRandomNetSwitch());
        NetSwitch obj = dod.getNewTransientNetSwitch(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'NetSwitch' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'NetSwitch' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NetSwitchIntegrationTest.testRemove() {
        NetSwitch obj = dod.getRandomNetSwitch();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NetSwitch' failed to provide an identifier", id);
        obj = NetSwitch.findNetSwitch(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'NetSwitch' with identifier '" + id + "'", NetSwitch.findNetSwitch(id));
    }
    
}
