// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sio.jnetmap.domain.Outlet;
import org.sio.jnetmap.domain.OutletDataOnDemand;
import org.sio.jnetmap.domain.OutletIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OutletIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OutletIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OutletIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OutletIntegrationTest: @Transactional;
    
    @Autowired
    private OutletDataOnDemand OutletIntegrationTest.dod;
    
    @Test
    public void OutletIntegrationTest.testCountOutlets() {
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", dod.getRandomOutlet());
        long count = Outlet.countOutlets();
        Assert.assertTrue("Counter for 'Outlet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OutletIntegrationTest.testFindOutlet() {
        Outlet obj = dod.getRandomOutlet();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to provide an identifier", id);
        obj = Outlet.findOutlet(id);
        Assert.assertNotNull("Find method for 'Outlet' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Outlet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OutletIntegrationTest.testFindAllOutlets() {
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", dod.getRandomOutlet());
        long count = Outlet.countOutlets();
        Assert.assertTrue("Too expensive to perform a find all test for 'Outlet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Outlet> result = Outlet.findAllOutlets();
        Assert.assertNotNull("Find all method for 'Outlet' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Outlet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OutletIntegrationTest.testFindOutletEntries() {
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", dod.getRandomOutlet());
        long count = Outlet.countOutlets();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Outlet> result = Outlet.findOutletEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Outlet' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Outlet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OutletIntegrationTest.testFlush() {
        Outlet obj = dod.getRandomOutlet();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to provide an identifier", id);
        obj = Outlet.findOutlet(id);
        Assert.assertNotNull("Find method for 'Outlet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOutlet(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Outlet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OutletIntegrationTest.testMergeUpdate() {
        Outlet obj = dod.getRandomOutlet();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to provide an identifier", id);
        obj = Outlet.findOutlet(id);
        boolean modified =  dod.modifyOutlet(obj);
        Integer currentVersion = obj.getVersion();
        Outlet merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Outlet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OutletIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", dod.getRandomOutlet());
        Outlet obj = dod.getNewTransientOutlet(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Outlet' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Outlet' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Outlet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OutletIntegrationTest.testRemove() {
        Outlet obj = dod.getRandomOutlet();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Outlet' failed to provide an identifier", id);
        obj = Outlet.findOutlet(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Outlet' with identifier '" + id + "'", Outlet.findOutlet(id));
    }
    
}
