// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.NetModuleDataOnDemand;
import org.sio.jnetmap.domain.OutletDataOnDemand;
import org.sio.jnetmap.domain.Port;
import org.sio.jnetmap.domain.PortDataOnDemand;
import org.sio.jnetmap.domain.VlanDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PortDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PortDataOnDemand: @Component;
    
    private Random PortDataOnDemand.rnd = new SecureRandom();
    
    private List<Port> PortDataOnDemand.data;
    
    @Autowired
    private NetModuleDataOnDemand PortDataOnDemand.netModuleDataOnDemand;
    
    @Autowired
    private OutletDataOnDemand PortDataOnDemand.outletDataOnDemand;
    
    @Autowired
    private VlanDataOnDemand PortDataOnDemand.vlanDataOnDemand;
    
    public Port PortDataOnDemand.getNewTransientPort(int index) {
        Port obj = new Port();
        setNumPort(obj, index);
        return obj;
    }
    
    public void PortDataOnDemand.setNumPort(Port obj, int index) {
        int numPort = index;
        obj.setNumPort(numPort);
    }
    
    public Port PortDataOnDemand.getSpecificPort(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Port obj = data.get(index);
        Long id = obj.getId();
        return Port.findPort(id);
    }
    
    public Port PortDataOnDemand.getRandomPort() {
        init();
        Port obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Port.findPort(id);
    }
    
    public boolean PortDataOnDemand.modifyPort(Port obj) {
        return false;
    }
    
    public void PortDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Port.findPortEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Port' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Port>();
        for (int i = 0; i < 10; i++) {
            Port obj = getNewTransientPort(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
