// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.sio.jnetmap.domain.Vlan;
import org.sio.jnetmap.domain.VlanDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect VlanDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VlanDataOnDemand: @Component;
    
    private Random VlanDataOnDemand.rnd = new SecureRandom();
    
    private List<Vlan> VlanDataOnDemand.data;
    
    public Vlan VlanDataOnDemand.getNewTransientVlan(int index) {
        Vlan obj = new Vlan();
        setNameVlan(obj, index);
        setNumVlan(obj, index);
        return obj;
    }
    
    public void VlanDataOnDemand.setNameVlan(Vlan obj, int index) {
        String nameVlan = "nameVlan_" + index;
        if (nameVlan.length() > 30) {
            nameVlan = nameVlan.substring(0, 30);
        }
        obj.setNameVlan(nameVlan);
    }
    
    public void VlanDataOnDemand.setNumVlan(Vlan obj, int index) {
        int numVlan = index;
        obj.setNumVlan(numVlan);
    }
    
    public Vlan VlanDataOnDemand.getSpecificVlan(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Vlan obj = data.get(index);
        Long id = obj.getId();
        return Vlan.findVlan(id);
    }
    
    public Vlan VlanDataOnDemand.getRandomVlan() {
        init();
        Vlan obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Vlan.findVlan(id);
    }
    
    public boolean VlanDataOnDemand.modifyVlan(Vlan obj) {
        return false;
    }
    
    public void VlanDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Vlan.findVlanEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Vlan' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Vlan>();
        for (int i = 0; i < 10; i++) {
            Vlan obj = getNewTransientVlan(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
