// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sio.jnetmap.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sio.jnetmap.domain.Vlan;
import org.sio.jnetmap.domain.VlanDataOnDemand;
import org.sio.jnetmap.domain.VlanIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VlanIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VlanIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VlanIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VlanIntegrationTest: @Transactional;
    
    @Autowired
    private VlanDataOnDemand VlanIntegrationTest.dod;
    
    @Test
    public void VlanIntegrationTest.testCountVlans() {
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", dod.getRandomVlan());
        long count = Vlan.countVlans();
        Assert.assertTrue("Counter for 'Vlan' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VlanIntegrationTest.testFindVlan() {
        Vlan obj = dod.getRandomVlan();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to provide an identifier", id);
        obj = Vlan.findVlan(id);
        Assert.assertNotNull("Find method for 'Vlan' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Vlan' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VlanIntegrationTest.testFindAllVlans() {
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", dod.getRandomVlan());
        long count = Vlan.countVlans();
        Assert.assertTrue("Too expensive to perform a find all test for 'Vlan', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Vlan> result = Vlan.findAllVlans();
        Assert.assertNotNull("Find all method for 'Vlan' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Vlan' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VlanIntegrationTest.testFindVlanEntries() {
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", dod.getRandomVlan());
        long count = Vlan.countVlans();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Vlan> result = Vlan.findVlanEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Vlan' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Vlan' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VlanIntegrationTest.testFlush() {
        Vlan obj = dod.getRandomVlan();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to provide an identifier", id);
        obj = Vlan.findVlan(id);
        Assert.assertNotNull("Find method for 'Vlan' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVlan(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Vlan' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VlanIntegrationTest.testMergeUpdate() {
        Vlan obj = dod.getRandomVlan();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to provide an identifier", id);
        obj = Vlan.findVlan(id);
        boolean modified =  dod.modifyVlan(obj);
        Integer currentVersion = obj.getVersion();
        Vlan merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Vlan' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VlanIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", dod.getRandomVlan());
        Vlan obj = dod.getNewTransientVlan(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Vlan' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Vlan' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Vlan' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VlanIntegrationTest.testRemove() {
        Vlan obj = dod.getRandomVlan();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Vlan' failed to provide an identifier", id);
        obj = Vlan.findVlan(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Vlan' with identifier '" + id + "'", Vlan.findVlan(id));
    }
    
}
